name: stepflow
description: Energy Pet - A health tracking app with a growth character.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  health: ^11.0.0
  permission_handler: ^11.3.0
  sqflite: ^2.3.2
  path: ^1.9.0
  fl_chart: ^0.66.0
  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pedometer: ^4.1.1
  shared_preferences: ^2.5.4
  flutter_foreground_task: ^9.2.0
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.png

dependency_overrides:
  intl: ^0.20.2
